- src/lib.rs
Hi!
I've copied Cesar Eduardo Barros' code from the [`constant_time_eq` crate](https://github.com/cesarb/constant_time_eq) (CC0).
It basically gives the compiler a hint that bounds checking is not necessary when iterating over the elements of the arrays. The speedup is noticeable, e.g. [here are some benches:](https://github.com/mp4096/rust-constant-time-comp-bench)
```
$ cargo bench
running 6 tests
test tests::bench_functional_generic                       ... bench:     107,932 ns/iter (+/- 1,759)
test tests::bench_functional_specialised                   ... bench:       4,568 ns/iter (+/- 99)
test tests::bench_imperative_generic                       ... bench:     107,690 ns/iter (+/- 1,671)
test tests::bench_imperative_generic_no_bound_checking     ... bench:      73,462 ns/iter …
```
> Improve `arrays_equal` performance by eliding bounds check

- src/lib.rs
This crate was 99% of the way there for no_std support. Here's the last 1%.
> Use no_std unless the "std" feature is present

- Cargo.toml
- README.md
- src/lib.rs
This changes `Mask = u8` to an opaque `Choice` type to let us insert optimization barriers without changing the external API.
The `Equal` trait is now implemented for slices, replacing the `slices_equal` method.
The array implementations are removed since they're quite complicated and aren't used.
I also refactored the documentation to move, e.g., feature descriptions into the `README.md`.
> Change `Mask = u8` to an opaque `Choice` and rework traits.

- src/lib.rs
Nightly Rust is only needed for 'asm'.
> 'nightly' is only needed for 'asm', as of rustc 1.26

- src/lib.rs
This ensures `std` and `no_std` consistently import the same crates, and makes adding `std` purely positive.
It's also a bit more straightforward and a pattern I'd like to encourage.
> Always use the #![no_std] directive

- Cargo.toml
- src/lib.rs
The generic implementations are now available at all times.
* CLOSES https://github.com/dalek-cryptography/subtle/issues/24
* CLOSES https://github.com/dalek-cryptography/subtle/issues/25
> Remove "generic-impls" feature gate

- Cargo.toml
- README.md
- src/lib.rs
- tests/mod.rs
Instead of having multiple traits with dependency relations, just have one
trait that has provided methods.  This allows maximum flexibility for the
implementor.
> Collapse into a single ConditionallySwappable with provided methods

- src/lib.rs
- tests/mod.rs
See #39.
The reason this came about is because we're implementing algorithms for field arithmetic in one of our crates and the current practice (as seen in `curve25519-dalek` for example) of
1. If you call `invert()` it returns zero for a zero input, when it should actually fail.
2. If you call inverse square root, it will return a value and a `Choice` indicating whether it's correct or not; the caller could accidentally forget.
is error prone. Given this new `Maybe` abstraction
1. Inversion can now return a `Maybe<T>` and if the caller is sure that the inputs are never zero, they can `unwrap()` themselves to make it explicit.
2. (Inverse) square root can return a `Maybe<T>` and the caller can choose how to deal with it. If they want to deal with the case in constant time, they can.
The …
> Introduce `Maybe` optional type

- .travis.yml
https://github.com/dalek-cryptography/subtle/blob/f6028bca3ffa81bb7202dd409ba69047099d2510/.travis.yml#L18-L19
This PR fixes the `no_std` build, by updating the travis config to modern rust-embedded guidelines. I chose the `thumbv7em-none-eabi` target, because I feel that these devices (in particular the ARM Cortex M4) are pretty popular in the crypto-engineering community.
> travis: Fix no-std build

- src/lib.rs
The previous assembly code required the compiler to move the value into memory to be able to pass the pointer into assembly. Often this also resulted in the function not being inlined. I believe this code is equivalent in terms of black box behavior but allows for much better codegen in the case where `input` is already in a register.
> Optimize black_box

- README.md
- src/lib.rs
This PR improves the implementation of `black_box`, using the fact that the semantics of `volatile` are pretty well defined. With this change, you could probably even omit `#[inline(never)]`, and then it may even be more efficient (I didn't benchmark).
> `// Bailing out, hopefully the compiler doesn't use the fact that ``input`` is 0 or 1.`
This patch also defines this case. ^
Example codegen: https://godbolt.org/z/3xYX1U
> Harden stable implementation of black_box

- README.md
- src/lib.rs
This is broken on nightly, since asm has been changed to llvm_asm. But rather
than fixing it, we can simply drop it, because we now have an optimization
barrier that works on stable Rust with no platform dependencies.
Also, update the README and docs to reflect this change.
Closes #70 #67
> Remove inline assembly.

- src/lib.rs
- tests/mod.rs
Uses XNOR on two `Choice` values to provide constant time equality comparisons.
I've seen this pattern a lot in code and thought it might be nice to wrap it up this way.
> Impl ConstantTimeEq for Choice

- .travis.yml
- README.md
- src/lib.rs
As stated in #73 and #74 the `CtOption<T>` API is a bit
unflexible when you try to extract the value from the
`CtOption` or you want to convert the `CtOption<T>`
into an `Option<T>` or a `Result<T>`.
Therefore the conversion from `CtOption<T>` to `Option<T>`
has been implemented to avoid having situations like:
```rust
if ct_opt.is_some() {
return ct_opt.unwrap()
} else {
return Err(....)
}
```
This impl is done to avoid ending up with unpractical, verbose and/or bad handled
conversions from the `CtOption<T>` wraps to an `Option<T>` or `Result<T, E>`.
This implementation doesn't intend to be constant-time nor try to protect the
leakage of the `T` since the `Option<T>` will do it anyways.
Closes #73
Closes #74
I wasn't sure about adding an `Unreleased` section on the `CHANGELOG.md` or just …
> Implement `From<CtOption<T>> for Option<T>

- Cargo.toml
- src/lib.rs
- tests/mod.rs
This would help implementers of some post-quantum algorithms which require constant-time sorting networks (such as lattice-based key exchanges [where strong anonymity guarantees are required](https://lists.torproject.org/pipermail/tor-dev/2016-May/010908.html)). Additionally, I think it helps some ancient outdated mode of RSA padding or something, but I don't really care about that. (cf. #20)
I also began implementing a ConstantTimePartialOrd based using these two traits (see #79) and using the `greater_than + greater_than - less_than - 1` trick that libsodium uses in `sodium_compare()` for unsigned integers, but I can't find a way to use Rust's `Ordering` structs without branching on the result, so while I'm posting the code for reference, it should absolutely not be merged.
This should …
> Add ConstantTime{Greater,Less}Than traits and impls for unsigned integers

- Cargo.toml
- src/lib.rs
The latest rust nightlies and beta (at stable version 1.55) include a
change from
#![cfg_attr(feature = "nightly", feature(external_doc))]
#![cfg_attr(feature = "nightly", doc(include = "../README.md"))]
to removing `feature(external_doc)` and also changing the syntax of
the second line to
#![cfg_attr(feature = "nightly", doc = include_str!("../README.md"))]
However.  `include_str!` is stable currently, but the syntax of `doc =
` is expressly disallowed.  This gives me four options:
1. Don't build documentation (bad)
2. Copy-pasta README.md into src/lib.rs (also bad)
3. Support only beta/nightly but not stable (completely untennable
for a crate with ~14 million downloads)
4. Support only stable but not beta/nightly (also untennable)
Further, waiting for this to be "fixed" by its inclusion …
> Fix external doc builds

- src/lib.rs
- tests/mod.rs
Adds a provided `ct_ne` method to `ConstantTimeEq` which provides the inverse of `ct_eq`.
> Add `ConstantTimeEq::ct_ne`

- src/lib.rs
Along the lines of the existing `CtOption::unwrap`, this adds a corresponding `CtOption::expect` which works like `Option::expect`: unwraps the value if it's some, or else panics with a provided error message.
Using `expect` over `unwrap` is generally prefered from a Rust style perspective. This allows the caller to describe what invariant was violated when it's expected some `CtOption` is always some.
> Add `CtOption::expect`

- src/lib.rs
Add constant time warning to `unwrap_or_else` doc comment so that the user knows that the closure will not be lazy evaluated.
> Add constant time warning to `unwrap_or_else`

- src/lib.rs
- tests/mod.rs
[`Ordering` is `#[repr(i8)]`](https://doc.rust-lang.org/src/core/cmp.rs.html#335), making it possible to impl the following traits for it by casting to `i8` (and back, where appropriate):
- `ConditionallySelectable`
- `ConstantTimeEq`
- `ConstantTimeGreater`
- `ConstantTimeLess`
> Add trait impls for `core::cmp::Ordering`

- .travis.yml
- Cargo.toml
- README.md
- fuzz/Cargo.toml
- fuzz/fuzzers/conditional_assign_array.rs
- src/lib.rs
PR makes arrays of any size "conditionally selectable" as long as `T` is conditionally selectable. Changes MSRV to 1.51.
Closes #82
> Implement `ConditionallySelectable` for `[T; N]`
